-- RLS-SCRIPT-RETRACTED-2026-09-07
--
-- THIS SCRIPT IS RETRACTED AND INTENTIONALLY EMPTY.
-- There is nothing here to execute. Do not restore its former body from git
-- history, and do not paste it into the Supabase SQL Editor or any other
-- client.
--
-- ============================================================================
-- WHY
-- ============================================================================
-- The former body looped over 31 public tables and, for each one, created a
-- policy of the shape `FOR ALL USING (true) WITH CHECK (true)` with no `TO`
-- clause.
--
-- PostgreSQL stores a policy with no `TO` clause as a grant to PUBLIC. On a
-- Supabase project, PUBLIC includes the unauthenticated `anon` role, and the
-- default `GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated`
-- is already in place. So the script's effect, had anyone run it, would have
-- been to hand unauthenticated read AND write on 31 tables -- including
-- `users`, `documents`, `financial_data`, `children` and `payments` -- to
-- anyone able to reach the project's Data API.
--
-- The script's own header claimed the opposite: that the policies "check for
-- service_role or NULL". They did not. Nothing in the former body ever named
-- a role.
--
-- ============================================================================
-- WAS IT EVER APPLIED?
-- ============================================================================
-- No. A controller-run, SELECT-only catalog snapshot of Production taken on
-- 2026-09-07 holds no policy under any of the prose names this script would
-- have created, and no policy on any public table whose grantee is PUBLIC.
-- Every public table already has row level security enabled, and every policy
-- present names exactly one of `anon`, `authenticated` or `service_role`.
--
-- The exposure was therefore always a REPOSITORY exposure: a runbook one
-- copy-paste away from creating the very hole it claimed to close. Retracting
-- the script closes that vector. No database change was made, and none is
-- required by this retraction.
--
-- ============================================================================
-- WHAT TO DO INSTEAD
-- ============================================================================
-- Row level security for this project is governed by tracked Prisma
-- migrations under `prisma/migrations/`, not by ad-hoc SQL Editor scripts.
-- A correct policy names its grantee explicitly, e.g.
--
--     ... FOR ALL TO service_role USING (true) WITH CHECK (true)
--
-- See `prisma/RLS_SETUP_GUIDE.md` for the current position, and
-- `20260506140500_enable_rls_remaining_public_tables` and
-- `20260804201000_enable_rls_checkout_security_tables` for worked examples.
--
-- `__tests__/security/no-permissive-public-rls-recipe.test.ts` fails the build
-- if a recipe granting unconditional permissive access to PUBLIC or `anon` is
-- ever committed again, in any tracked `.sql` or `.md` file.
